feat: Multi-platform build for `mender-convert`
This commit changes several things with the end goal of making the tool
multi-platform, namely easing the use of it on Apple M1 machines.

In short:
* Update base image to latest Ubuntu and update a dependency
* Modify Dockerfile to build platform aware images with buildx
* Switch pxz build image to Debian for easier cross-compile
* Use specific version of `mender-artifact` instead of master. The
  motivation of this specific change is to make easier the install of
  pre-built binares via deb package.
* Replace custom build/publish jobs for CI/CD with the ones from our
  templates, which are multi-platform ready
* Demote the `docker-build` script for local development only.

Changelog: `mender-convert` Docker build is now architecture aware and
it will install the native dependencies for the target architecture.
This change makes the tool compatible with Apple arm machines. The Docker
images will be published for `linux/amd64` and `linux/arm64` platforms.

Ticket: None

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

diff --git a/docker-build b/docker-build
--- a/docker-build
+++ b/docker-build
@@ -17,7 +17,7 @@
 set -e
 
 GIT_PROVIDED_TAG_NAME="$(git describe --exact HEAD 2>/dev/null || \
-    git for-each-ref "refs/heads/*" --format '%(refname:short)' --points-at HEAD 2>/dev/null)"
+    git for-each-ref "refs/heads/*" --format '%(refname:short)' --points-at HEAD 2>/dev/null | head -n1)"
 
 if [ -z "$IMAGE_NAME" -a -z "$GIT_PROVIDED_TAG_NAME" ]; then
   echo "Could not deduce mendersoftware/mender-convert container version from currently checked out commit. Using latest." 1>&2
@@ -25,4 +25,11 @@ fi
 
 IMAGE_NAME=${IMAGE_NAME:-"mendersoftware/mender-convert${GIT_PROVIDED_TAG_NAME:+:$GIT_PROVIDED_TAG_NAME}"}
 
-eval docker build . -t "${IMAGE_NAME}" "$*"
+MENDER_ARTIFACT_VERSION=$(sed -n '/MENDER_ARTIFACT_VERSION:/{n;s/.*value: "\(.*\)".*/\1/p;}' .gitlab-ci.yml)
+if [ -z "$MENDER_ARTIFACT_VERSION" ]; then
+  echo "Could not parse  MENDER_ARTIFACT_VERSION from .gitlab-ci.yml" 1>&2
+  exit 1
+fi
+
+echo "Building ${IMAGE_NAME} for local development" 1>&2
+docker build -t "${IMAGE_NAME}" --build-arg MENDER_ARTIFACT_VERSION="${MENDER_ARTIFACT_VERSION}" .
